apiVersion: apps/v1
kind: Deployment
metadata:
  name: linken-zipkin
  namespace: linken
spec:
  selector:
    matchLabels:
      app: linken-zipkin
  template:
    metadata:
      labels:
        app: linken-zipkin
    spec:
      containers:
      - image: openzipkin/zipkin
        imagePullPolicy: IfNotPresent
        name: linken-zipkin
        ports:
        - containerPort: 9411
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: linken-zipkin-svc
  namespace: linken
spec:
  selector:
    app: linken-zipkin
  type: NodePort
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411